apiVersion: v1
kind: Service
metadata:
  name: devops-fullstack-app
spec:
  selector:
    app: devops-fullstack-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort